# Generated by Django 6.0 on 2025-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novenaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology')], max_length=50)),
                ('doctor', models.CharField(choices=[('dr_amit', 'Dr. Amit Sharma'), ('dr_rahul', 'Dr. Rahul Verma'), ('dr_neha', 'Dr. Neha Singh'), ('dr_pooja', 'Dr. Pooja Gupta')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
