# Generated by Django 6.0 on 2025-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novenaApp', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstribeFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
